import { library } from '@fortawesome/fontawesome-svg-core';
import { fab } from '@fortawesome/free-brands-svg-icons';
import {
  faWrench, faTools, faCogs, faChartBar, faChartLine, faChartPie,
  faBoxes, faBox, faBoxOpen, faTruck, faWarehouse,
  faUsers, faUserCog, faUserTie,
  faCalendar, faCalendarCheck, faCalendarWeek, faClock,
  faBuilding, faIndustry, faMapMarkerAlt, faMapPin,
  faPlus, faEdit, faTrash, faEye, faSearch, faDownload,
  faFileExport, faFileInvoice, faFilePdf, faFileExcel,
  faBell, faEnvelope, faPhone, faGlobe,
  faCheck, faTimes, faExclamationTriangle, faInfoCircle,
  faChevronLeft, faChevronRight, faChevronDown,
  faHome, faSignOutAlt, faBars, faFilter, faSort, faPrint, faShare,
  faArrowRight, faArrowLeft, faArrowUp, faArrowDown,
  faSave, faUndo, faRedo, faCog,
  faClipboardList, faClipboardCheck, faTasks,
  faTachometerAlt, faGauge,
  faCircle, faSquare, faSpinner,
  faSun, faMoon, faLightbulb,
  faTag, faTags, faQrcode, faBarcode,
  faLock, faLockOpen, faKey,
  faPlay, faPause, faHistory,
  faHandshake, faShieldAlt, faHardHat,
  faDollarSign,
  faRecycle,
  faCubes, faLayerGroup,
  faServer, faDatabase, faMicrochip,
  faExclamationCircle, faCheckCircle,
} from '@fortawesome/free-solid-svg-icons';

library.add(
  fab,
  faWrench, faTools, faCogs, faChartBar, faChartLine, faChartPie,
  faBoxes, faBox, faBoxOpen, faTruck, faWarehouse,
  faUsers, faUserCog, faUserTie,
  faCalendar, faCalendarCheck, faCalendarWeek, faClock,
  faBuilding, faIndustry, faMapMarkerAlt, faMapPin,
  faPlus, faEdit, faTrash, faEye, faSearch, faDownload,
  faFileExport, faFileInvoice, faFilePdf, faFileExcel,
  faBell, faEnvelope, faPhone, faGlobe,
  faCheck, faTimes, faExclamationTriangle, faInfoCircle,
  faChevronLeft, faChevronRight, faChevronDown,
  faHome, faSignOutAlt, faBars, faFilter, faSort, faPrint, faShare,
  faArrowRight, faArrowLeft, faArrowUp, faArrowDown,
  faSave, faUndo, faRedo, faCog,
  faClipboardList, faClipboardCheck, faTasks,
  faTachometerAlt, faGauge,
  faCircle, faSquare, faSpinner,
  faSun, faMoon, faLightbulb,
  faTag, faTags, faQrcode, faBarcode,
  faLock, faLockOpen, faKey,
  faPlay, faPause, faHistory,
  faHandshake, faShieldAlt, faHardHat,
  faDollarSign,
  faRecycle,
  faCubes, faLayerGroup,
  faServer, faDatabase, faMicrochip,
  faExclamationCircle, faCheckCircle,
);
